//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CartGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CartGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AmbushFullMinCard {
            get {
                object obj = ResourceManager.GetObject("AmbushFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AmbushNormalCard {
            get {
                object obj = ResourceManager.GetObject("AmbushNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B1FullMin {
            get {
                object obj = ResourceManager.GetObject("B1FullMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B1NormalCard {
            get {
                object obj = ResourceManager.GetObject("B1NormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Beagle {
            get {
                object obj = ResourceManager.GetObject("Beagle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BeagleFillMinCard {
            get {
                object obj = ResourceManager.GetObject("BeagleFillMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigAttackFullMinCard {
            get {
                object obj = ResourceManager.GetObject("BigAttackFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigAttackNormalCard {
            get {
                object obj = ResourceManager.GetObject("BigAttackNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BombAttackFullMinCard {
            get {
                object obj = ResourceManager.GetObject("BombAttackFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BombAttackNormalCard {
            get {
                object obj = ResourceManager.GetObject("BombAttackNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BoxerFullMinCard {
            get {
                object obj = ResourceManager.GetObject("BoxerFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BoxerNormalCard {
            get {
                object obj = ResourceManager.GetObject("BoxerNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CarteMin {
            get {
                object obj = ResourceManager.GetObject("CarteMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap damage {
            get {
                object obj = ResourceManager.GetObject("damage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс карты: Оборонительное сооружение.
        /// </summary>
        internal static string DefenderConstrClass {
            get {
                return ResourceManager.GetString("DefenderConstrClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DestroyerFullMinCard {
            get {
                object obj = ResourceManager.GetObject("DestroyerFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DestroyerNormalCarte {
            get {
                object obj = ResourceManager.GetObject("DestroyerNormalCarte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DuelistFullMinCard {
            get {
                object obj = ResourceManager.GetObject("DuelistFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DuelistNormalCard {
            get {
                object obj = ResourceManager.GetObject("DuelistNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmptyCarteNormal {
            get {
                object obj = ResourceManager.GetObject("EmptyCarteNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EventCard {
            get {
                object obj = ResourceManager.GetObject("EventCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FieldRepairsFullMin {
            get {
                object obj = ResourceManager.GetObject("FieldRepairsFullMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FieldRepairsNormalCard {
            get {
                object obj = ResourceManager.GetObject("FieldRepairsNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ForceField {
            get {
                object obj = ResourceManager.GetObject("ForceField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ForceFieldFullMinCard {
            get {
                object obj = ResourceManager.GetObject("ForceFieldFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FullMinCarte {
            get {
                object obj = ResourceManager.GetObject("FullMinCarte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GladiatorFullMinCard {
            get {
                object obj = ResourceManager.GetObject("GladiatorFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GladiatorNormalCard {
            get {
                object obj = ResourceManager.GetObject("GladiatorNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете добавить эту карту на свое игровое поле..
        /// </summary>
        internal static string HelpAddMargin {
            get {
                return ResourceManager.GetString("HelpAddMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наносит урон все картам, находящимся на поле врага. Для этого перетащиет карту на поле высадки карт противника..
        /// </summary>
        internal static string HelpAllDamageEvent {
            get {
                return ResourceManager.GetString("HelpAllDamageEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете атаковать карты противника, находящиеся на его игровом поле..
        /// </summary>
        internal static string HelpAttackDefenderConstr {
            get {
                return ResourceManager.GetString("HelpAttackDefenderConstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете атаковать штаб и карты противника, находящиеся на его игровом поле..
        /// </summary>
        internal static string HelpAttackRobot {
            get {
                return ResourceManager.GetString("HelpAttackRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HelpCardsGame {
            get {
                object obj = ResourceManager.GetObject("HelpCardsGame", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpCardsGame1 {
            get {
                object obj = ResourceManager.GetObject("helpCardsGame1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пятиугольник - урон, наносимы данной картой по противнику.
        ///Шестиугольник - очки прочности данной карты..
        /// </summary>
        internal static string HelpCardsMargin {
            get {
                return ResourceManager.GetString("HelpCardsMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете нанести урон штабу или роботу врага на игровом поле. 
        ///Для этого перетащите событие к нужной карте..
        /// </summary>
        internal static string HelpDamageEvent {
            get {
                return ResourceManager.GetString("HelpDamageEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс данной карты: Защитное сооружение
        ///Треугольник - цена добавления защитного сооружения, на игровое поле
        ///Пятиугольник - урон, наносимы данным защитным сооружением по противнику
        ///Шестиугольник - очки прочности данной карты
        ///Защитные сооружения не могут атаковать штаб.
        /// </summary>
        internal static string HelpDefenderConstr {
            get {
                return ResourceManager.GetString("HelpDefenderConstr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс данной карты: Событие
        ///Треугольник - цена использования события
        ///Пятиугольник - количество очков, добавляемых/забираемых
        ///данным событием.
        /// </summary>
        internal static string HelpEvent {
            get {
                return ResourceManager.GetString("HelpEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете добавить очки прочности штабу. Для  этого перетащите карту на свой штаб..
        /// </summary>
        internal static string HelpHQRepairs {
            get {
                return ResourceManager.GetString("HelpHQRepairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы можете добавить очки прочности штабу или роботу на игровом поле. 
        ///Для этого перетащите событие к нужной карте..
        /// </summary>
        internal static string HelpRepairsEvent {
            get {
                return ResourceManager.GetString("HelpRepairsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс данной карты: Робот
        ///Треугольник - цена добавления робота, на игровое поле
        ///Пятиугольник - урон, наносимы данным роботом по противнику
        ///Шестиугольник - очки прочности данной карты.
        /// </summary>
        internal static string HelpRobot {
            get {
                return ResourceManager.GetString("HelpRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HQCardMax {
            get {
                object obj = ResourceManager.GetObject("HQCardMax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс карты: Штаб.
        /// </summary>
        internal static string HQClass {
            get {
                return ResourceManager.GetString("HQClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HQMinCarte {
            get {
                object obj = ResourceManager.GetObject("HQMinCarte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Huntsman {
            get {
                object obj = ResourceManager.GetObject("Huntsman", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HuntsmanFullMinCard {
            get {
                object obj = ResourceManager.GetObject("HuntsmanFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InvertedCarte {
            get {
                object obj = ResourceManager.GetObject("InvertedCarte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MedicFullMinlCart {
            get {
                object obj = ResourceManager.GetObject("MedicFullMinlCart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MedicNormalCart {
            get {
                object obj = ResourceManager.GetObject("MedicNormalCart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointAttackSpaceCarteNormal {
            get {
                object obj = ResourceManager.GetObject("PointAttackSpaceCarteNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointAttackSpaceFullMin {
            get {
                object obj = ResourceManager.GetObject("PointAttackSpaceFullMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecruitFullMinCard {
            get {
                object obj = ResourceManager.GetObject("RecruitFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecruitNormalCard {
            get {
                object obj = ResourceManager.GetObject("RecruitNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RepairsBoxFullMin {
            get {
                object obj = ResourceManager.GetObject("RepairsBoxFullMin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RepairsBoxNormalCard {
            get {
                object obj = ResourceManager.GetObject("RepairsBoxNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс карты: Робот.
        /// </summary>
        internal static string RobotClass {
            get {
                return ResourceManager.GetString("RobotClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RocketFullMinCard {
            get {
                object obj = ResourceManager.GetObject("RocketFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RocketNormalCard {
            get {
                object obj = ResourceManager.GetObject("RocketNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpentEnergy {
            get {
                object obj = ResourceManager.GetObject("SpentEnergy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StockEnergy {
            get {
                object obj = ResourceManager.GetObject("StockEnergy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestCart {
            get {
                object obj = ResourceManager.GetObject("TestCart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurretFullMinCard {
            get {
                object obj = ResourceManager.GetObject("TurretFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TurretNormalCard {
            get {
                object obj = ResourceManager.GetObject("TurretNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VeteranFullMinCard {
            get {
                object obj = ResourceManager.GetObject("VeteranFullMinCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VeteranNormalCard {
            get {
                object obj = ResourceManager.GetObject("VeteranNormalCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
